// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXRmJHDGg_tGz8Q8QM9HjHxI5dB-sZWe4',
    appId: '1:358167438086:web:3ad7796e8ca58f9a59b487',
    messagingSenderId: '358167438086',
    projectId: 'korean-writing-app-6c4f6',
    authDomain: 'korean-writing-app-6c4f6.firebaseapp.com',
    storageBucket: 'korean-writing-app-6c4f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLmGFsZ6nKw_ulbgHUqWdYfhOuaUQ7Gf4',
    appId: '1:358167438086:android:9a0ce3e43f43edf759b487',
    messagingSenderId: '358167438086',
    projectId: 'korean-writing-app-6c4f6',
    storageBucket: 'korean-writing-app-6c4f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg7vvEFburp11LbCuERcpkJdYwa9xqtlM',
    appId: '1:358167438086:ios:c2b72dcc240b4d0b59b487',
    messagingSenderId: '358167438086',
    projectId: 'korean-writing-app-6c4f6',
    storageBucket: 'korean-writing-app-6c4f6.firebasestorage.app',
    iosBundleId: 'com.example.koreanWritingAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg7vvEFburp11LbCuERcpkJdYwa9xqtlM',
    appId: '1:358167438086:ios:c2b72dcc240b4d0b59b487',
    messagingSenderId: '358167438086',
    projectId: 'korean-writing-app-6c4f6',
    storageBucket: 'korean-writing-app-6c4f6.firebasestorage.app',
    iosBundleId: 'com.example.koreanWritingAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXRmJHDGg_tGz8Q8QM9HjHxI5dB-sZWe4',
    appId: '1:358167438086:web:99d80cb1f76955ea59b487',
    messagingSenderId: '358167438086',
    projectId: 'korean-writing-app-6c4f6',
    authDomain: 'korean-writing-app-6c4f6.firebaseapp.com',
    storageBucket: 'korean-writing-app-6c4f6.firebasestorage.app',
  );
}
